version: "3.7"

services:
   tika:
    container_name: 'tika'
    image: apache/tika:1.25-full
    # Override default so we can add configuration on classpath
    entrypoint: [ "/bin/sh", "-c", "exec java -cp tika-server-1.25.jar org.apache.tika.server.TikaServerCli -h 0.0.0.0 $$0 $$@"]
    # Kept command as example but could be added to entrypoint too
    command: -c /tika-config.xml
    restart: on-failure
    ports:
      - "9998:9998"
    #volumes:
      # Choose the configuration you want, or add your own custom one
      # -  ./sample-configs/customocr/tika-config-inline.xml:/tika-config.xml
      -  ./sample-configs/customocr/tika-config-rendered.xml:/tika-config.xml
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    environment:
      # The location of the RabbitMQ server.  "amqp" is the protocol;
      # "rabbitmq" is the hostname.  Note that there is not a guarantee
      # that the server will start first!  Telling the pika client library
      # to try multiple times gets around this ordering issue.
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      RABBITMQ_DEFAULT_USER: "openedgar"
      RABBITMQ_DEFAULT_PASS: "openedgar"
    networks:
      - openedgar
  rabbitmq:
    container_name: 'rabbitmq'
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    environment:
      # The location of the RabbitMQ server.  "amqp" is the protocol;
      # "rabbitmq" is the hostname.  Note that there is not a guarantee
      # that the server will start first!  Telling the pika client library
      # to try multiple times gets around this ordering issue.
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      RABBITMQ_DEFAULT_USER: "openedgar"
      RABBITMQ_DEFAULT_PASS: "openedgar"
    networks:
      - openedgar
networks:
  # Declare our private network.  We must declare one for the magic
  # Docker DNS to work, but otherwise its default settings are fine.
  openedgar: {}